apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-pipeline-agent-config
  namespace: jesa-med-ns
data:
  AZP_URL: "https://dev.azure.com/soulredouane40"
  AZP_POOL: "Default"
  AZP_AGENT_NAME: "jesa-med-job-agent"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: azp-agent-job
  namespace: jesa-med-ns
spec:
  activeDeadlineSeconds: 1200  # Auto-stop after 20 min
  ttlSecondsAfterFinished: 300 # Delete 5 min after completion
  template:
    metadata:
      labels:
        app: azp-agent
      annotations:
        vault.hashicorp.com/agent-pre-populate-only: "true"  # this ensure not sidecar only init container, so it will make the job completed
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-role"
        vault.hashicorp.com/agent-inject-secret-login: "secret/data/login"
        vault.hashicorp.com/agent-inject-template-login: |
          {{- with secret "secret/data/login" -}}
          export AZP_TOKEN="{{ .Data.data.AZP_TOKEN }}"
          {{- end }}
    spec:
      serviceAccountName: vault-access-sa
      containers:
        - name: azp-agent
          image: soulredouane/azure-agent-php:v4
          command: ["/bin/sh", "-c"]
          args: ["cp /azp/html.tpl /shared/ && . /vault/secrets/login && /azp/start.sh"]
          imagePullPolicy: Always
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
          envFrom:
            - configMapRef:
                name: azure-pipeline-agent-config
          volumeMounts:
            - name: shared-data
              mountPath: /shared
        - name: dind
          image: docker:dind
          securityContext:
            privileged: true
          env:
            # Disable TLS by setting DOCKER_TLS_CERTDIR to an empty value
            - name: DOCKER_TLS_CERTDIR
              value: ""
          volumeMounts:
            - name: shared-data
              mountPath: /shared
      volumes:
        - name: certs
          emptyDir: {}
        - name : shared-data
          emptyDir: {}
      restartPolicy: Never
