apiVersion: batch/v1
kind: Job
metadata:
  name: azp-agent-job
  namespace: jesa-med-ns
spec:
  activeDeadlineSeconds: 1200  # Auto-stop after 20 min
  ttlSecondsAfterFinished: 300 # Delete 5 min after completion
  template:
    metadata:
      labels:
        app: azp-agent
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-role"
        vault.hashicorp.com/agent-inject-secret-login: "secret/data/login"
        vault.hashicorp.com/agent-inject-template-login: |
          {{- with secret "secret/data/login" -}}
          export AZP_TOKEN="{{ .Data.data.AZP_TOKEN }}"
          {{- end }}
    spec:
      serviceAccountName: vault-access-sa
      containers:
        - name: azp-agent
          image: soulredouane/azure-agent-php:v2
          command: ["/bin/sh", "-c"]
          args: [". /vault/secrets/login && /azp/start.sh"]
          imagePullPolicy: Always # Never
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2376
            - name: DOCKER_TLS_VERIFY
              value: "1"
            - name: DOCKER_CERT_PATH
              value: /certs/client
          envFrom:
            - configMapRef:
                name: azure-pipeline-agent-config
        - name: dind
          image: docker:dind
          securityContext:
            privileged: true
          env:
          - name: DOCKER_TLS_CERTDIR
            value: /certs/client
      volumes:
        - name: certs
          emptyDir: {}
      restartPolicy: Never
