apiVersion: batch/v1
kind: Job
metadata:
  name: azp-agent-job
  namespace: jesa-med-namespace  # Fixed typo in 'namespace'
spec:
  activeDeadlineSeconds: 1200  # Auto-stop after 20 min
  ttlSecondsAfterFinished: 300 # Delete 5 min after completion
  template:
    metadata:
      labels:
        app: azp-agent
    spec:
      containers:
      - name: azp-agent
        image: soulredouane/azure-agent-k8s:v1
        securityContext:
          privileged: true      # Fixed indentation
          runAsUser: 0          # Changed from string to number
        imagePullPolicy: Always # Fixed indentation
        envFrom:
        - configMapRef:
            name: azure-pipeline-agent-config
        env:
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: azp-token
              key: token
        lifecycle:
          preStop:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "/azp/config.sh remove --unattended --auth PAT --token $(cat /azp/.token)"
      restartPolicy: Never
