apiVersion: v1
kind: Pod
metadata:
  name: download-report-pod
  # namespace: jesa-med-ns  # Match your namespace
spec:
  containers:
  - name: report-uploader
    image: curlimages/curl:latest  # Lightweight image with curl
    command: ["/bin/sh", "-c"]
    args:
    - |
      echo "Listing reports in /report..." && \
      ls -la /report/jesa-med && \
      
      # Find the report file
      REPORT_FILE=$(ls /report/jesa-med/owasp-report-${REPORT_ID}/dependency-check-report.html) && \
      echo "Found report file: $REPORT_FILE" && \
      
      # Copy the report to a local directory
      mkdir -p /output/dependency-check-report && \
      cp "$REPORT_FILE" /output/dependency-check-report/dependency-check-report.html && \
      ls -la /output/dependency-check-report && \
      
      # Keep the pod running for debugging (optional)
      echo "Task completed, keeping pod alive..." && \
      sleep infinity
    env:
    - name: AZP_TOKEN  # Azure DevOps PAT for authentication
      valueFrom:
        secretKeyRef:
          name: azure-devops-pat  # Ensure this secret exists
          key: pat
    - name: ORGANIZATION
      valueFrom:
        configMapKeyRef:
          name: git-repo
          key: ORGANIZATION
    - name: PROJECT
      valueFrom:
        configMapKeyRef:
          name: git-repo
          key: PROJECT
    - name: REPORT_ID
      valueFrom:
        configMapKeyRef:
          name: report-config
          key: REPORT_ID
    - name: BUILD_ID
      valueFrom:
        configMapKeyRef:
          name: report-config
          key: TAG  # Ensure this key exists in report-config ConfigMap
    volumeMounts:
    - name: report-volume
      mountPath: /report
    - name: output-volume
      mountPath: /output  # Added to persist the copied file
    securityContext:
      runAsUser: 0  # Run as root to ensure write permissions
  volumes:
  - name: report-volume
    persistentVolumeClaim:
      claimName: dependency-check-report  # Same PVC as the dependency-check Job
  - name: output-volume
    emptyDir: {}  # Local storage for the copied report
  restartPolicy: Never  # Pod won't restart if it exits
